# Generated by Django 6.0.3 on 2026-03-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='complaint_videos/'),
        ),
    ]
